---
title: "sok-2011 seminar"
format: pdf
editor: visual
---


Seminar
– Tiltak for bærekraftig utvikling
SOK-2011


## Oppgave
### 1. Velg en av de to fenomenene (du kan også velge et annet problem som du selv identifiserer).
### 2. På hvilke måter utfordres bærekraften i utviklingen?
• Tenk på sosiale effekter, miljøeffekter, økonomiske effekter, og kombinasjoner av disse
• Tenk både på effekter på dagens generasjon og framtidige generasjoner
### 3. Kan du komme på et tiltak som reduserer de negative effektene?
• Om du ikke kommer på et tiltak kan du analysere et eksisterende tiltak knyttet til temaet
### 4. Diskuter effekter (positive og negative) av tiltaket.
• Prøv å inkludere effekter utenom den sektoren som blir direkte påvirket.
### 5. Hvordan får vi alle med på laget?
• Prøv å tenke på politiske utfordringer og muligheter

## Notater

venndiagramet mellom natur sosial og økonomisk.
Regulering
Skatter, avgifter og tolleffekter
Selvregulering, nudging


til nr3
diskutere positive og negative effekter av tiltaket

Del av muntlig eksamen er presentasjon om bærekraftig utvikling. forklare hva det er, hvorfor det er vanskelig for private. diskutere effekteer av et eksempel på politisk tiltak. kan også være et tiltak. må ikke være nytt men kan bruke noe som har vært gått igjennom på kurset. Kan lage selv men knyt til kurset og andrea ønsker dette.


nr5
hvordan får vi alle med, er det upoulært? veldig dyrt? eller er det noe vi kan med folk på


## Oppgave besvarelse

1: Velger cruiseship som fenomen i Tromsø






2: Bærekraften utfordres naturmessig ved at cruiseship slipper ut mye co2. søppel, nox, avløp osv. 

Sosialt utfordres bærekraften ved at cruiseshipene tar opp mye plass i byen og at det er mange turister som kommer. Butikkene i byen mister lokale kunder og det dukker opp nye turistbutikker som gjør at lokale ikke kommer. Sosial tilitt kan reduseres over at lokale føler mindre samhold med byen. Folk går på feil siden av brua osv.


Økonomisk utfordres bærekraften ved at passasjerene benytter alle tjenestene i byen men de ikke gir så mye tilbake til byen. 
Etterspørsel etter byens tjenester øker, og dersom turistene ikke betaler noe form for skatt så kommer regningen på lokale. sliter infrastruktur, bruker søppelbøtter, offentlige toaletter osv.


3: Tiltak som reduserer negative effekter.
Skipene må tilkobles landstrøm. Dette vil redusere co2 utslippene. Dette gjøres allerede med fly. 

Turistskatt på cruiseship. Dette vil gi inntekter til byen og gjøre at de som kommer til byen betaler for seg. 



4. Diskutere positive og negative effekter av tiltaket.
• Prøv å inkludere effekter utenom den sektoren som blir direkte påvirket.

Positive effekter:
- Redusert co2 utslipp
- Turistskatt kan hjelpe med å finansiere landstrøm og øke inntekter til byen som kan dekke kostnader for turistene.


Negative effekter:
- Skipene må da også fornyes og kan kanskje ikke ha mulighet å bygge inn denne muligheten.
- Turistene kan velge å dra til andre steder.
- med skatt så vil turistene ha mindre penger å bruke på lokalt næringsliv.




5. Hvordan får vi alle med på laget?
• Prøv å tenke på politiske utfordringer og muligheter

Politisk utfordring:
Vanskelig å innføre å treffe turistene som kommer som folk som bor i telt osv. uten å treffe jobbturer og sånt.
Mye næringsliv tjener på turistene og de vil ikke ha skatt. og hvordan dekker man opp for de som mister inntekt på turistene som ikke kommer og det reduserte forbruket da mer penger går til det offentlige.

Muligheter:











